### ISSUE TITLE
refer suffix is omitted

### ISSUE THREAD

**Issue by cloudace-satou** [0Delta/py-interactive_input#1]
## Improve details
If the refer string is long, the end is omitted.
<img width="810" alt="スクリーンショット 2020-03-10 12 03 03" src="https://user-images.githubusercontent.com/44155483/76275842-a9806780-62c7-11ea-9d53-590822278204.png">

## Expected behavior
Refers to the end regardless of the length of the string.

**Comment by 0Delta** [comment]
`Refer` does not exist this package. 
I think this is probably `Message`

This behavior is safe for very long message or very small console.
More case, input value is important more than message.
However, this behavior is inconvenient for some developers.

So, I released `wrap` option at `v.0.5.0` !
Enjoy ;)
